# Colors
RESET=%{$reset_color%}
CYAN=%{$FG[122]%}
PINK=%{$FG[175]%}
GREEN=%{$FG[155]%}
RED=%{$FG[166]%}

# Git
BRANCH="\ue0a0"
ZSH_THEME_GIT_PROMPT_PREFIX="$BRANCH "
ZSH_THEME_GIT_PROMPT_SUFFIX=""
ZSH_THEME_GIT_PROMPT_DIRTY="$RED ✗$RESET"
ZSH_THEME_GIT_PROMPT_CLEAN="$GREEN ✔$RESET"

# Prompt
PRE="$PINK %T %Bλ%b $RESET"
DIR="$CYAN%B%2/%b$RESET"

PROMPT='$PRE$DIR $(git_prompt_info) $CYAN➤$RESET '

